apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DB: YXBpX2Ri
  POSTGRES_USER: YXBpX3VzZXI=
  POSTGRES_PASSWORD: cGdfcGFzc3dvcmQ=
  POSTGRES_CONNECTION_STRING: ZGJuYW1lPWFwaV9kYiB1c2VyPWFwaV91c2VyIHBhc3N3b3JkPXBnX3Bhc3N3b3JkIHBvcnQ9NTQzMiBob3N0PWRi