version: '3.2'
services:
  api:
    container_name: 'my-api'
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:12
    ports:
      - 5433:5432